#!/usr/bin/env python3
"""Builds the generated text filter plugins in data/filters from the pinned SCOWL lists.

Each plugin is a table (or token) form .sfilter whose rule is data taken from a dictionary, so it
is made by this script rather than by hand, as tools/moby_pos.py makes the grammar's lists. The
output is a pure function of the input files, which are checked against the SHA-256 the
dictionary registry pins (data/dictionaries/dictionaries.tsv); every number written is an integer
worked out exactly, so the same lists give the same files, byte for byte, on any machine.

    letter-pairs-v1      lower27  no letter pair inside a word that no word of the list has
    letter-triples-v1    lower27  the same for three letters (word starts and ends included)
    word-cost-v1         lower27  no stretch of a word costs more than the budget under a
                                  letter-pair model of the list (a leaky bucket, exact)
    function-words-v1    lower27  a few rules on the commonest function words ("the the", "a of")
    sentence-shape-v1    ascii95  punctuation and capitals where sentences put them
    babel-punctuation-v1 babel29  commas and full stops where sentences put them

A plugin is versioned by its bytes: run this again on the same lists and the files do not change.
A changed rule (other lists, other thresholds, a fix) is a new version, written beside the old.

    python tools/build_text_plugins.py            # writes them into data/filters
    python tools/build_text_plugins.py --check    # fails if a written file would differ
"""

import argparse
import collections
import hashlib
import os
import string
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DICTS = os.path.join(ROOT, "data", "dictionaries")
OUT = os.path.join(ROOT, "data", "filters")
LETTERS = string.ascii_lowercase
AUTHOR = "Edward James Gordon (written with Claude)"

# min_words: a letter group is allowed when at least this many words of the list contain it. The
# counts at or above the cap are always allowed; the ones below it are grouped under `if`s, so the
# threshold is a setting of the plugin rather than a new file.
MIN_WORDS_CAP = 10


def registry():
    rows = {}
    for line in open(os.path.join(DICTS, "dictionaries.tsv"), encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        f = line.rstrip("\n").split("\t")
        rows[f[0]] = (f[1], f[4])
    return rows


def words_of(dict_id):
    """The list's words, folded to lower case (as the lower-case alphabets read it), once each."""
    name, sha = registry()[dict_id]
    data = open(os.path.join(DICTS, name), "rb").read()
    got = hashlib.sha256(data).hexdigest()
    if got != sha:
        sys.exit(f"{name}: SHA-256 {got} is not the registry's {sha}")
    words = sorted({w.strip().lower() for w in data.decode("utf-8").splitlines() if w.strip()})
    return words, sha


def header(fmt, ident, symbols, describe, comment, source, sha):
    lines = [fmt]
    lines += ["; " + c if c else ";" for c in comment]
    lines += [f"; Generated by tools/build_text_plugins.py from {source} (sha256 {sha}).",
              f"id        {ident}", "version   1", f"author    {AUTHOR}", "origin    ai-directed",
              "lines     text", f"symbols   {symbols}", f"describe  {describe}"]
    return lines


def q(ch):
    return '" "' if ch == " " else f'"{ch}"'


def grouped(trans):
    """Transitions (from, symbol, to, count) as lines: certain ones first, then one if block per
    count below the cap."""
    out, by = [], collections.defaultdict(list)
    for f, s, t, n in sorted(trans):
        if n >= MIN_WORDS_CAP:
            out.append(f"t {f} {q(s)} {t}")
        else:
            by[n].append(f"  t {f} {q(s)} {t}")
    for n in sorted(by):
        out.append(f"if {{min_words <= {n}}}")
        out += by[n]
        out.append("fi")
    return out


# ---------------------------------------------------------------------------------------------
# Letter pairs and triples.
#
# A word is read padded with a boundary at each end ("^cat^"). A page can be cut from running text
# anywhere, so the unit's first characters may be the middle of a word: at the start nothing is
# known (state U) and the first letter is free, and the unit's end is never judged. A SPACE is a
# boundary; spaces after spaces are always allowed (double spaces are clean's business, and the
# padding at the end of the last unit of warped text is spaces).


def ngram_counts(words, n):
    c = collections.Counter()
    for w in words:
        p = "^" + w + "^"
        c.update({p[i:i + n] for i in range(len(p) - n + 1)})
    return c


def letter_pairs(words, sha, source):
    c2 = ngram_counts(words, 2)
    U, B = 0, 1
    st = {ch: 2 + i for i, ch in enumerate(LETTERS)}
    trans = []
    for ch in LETTERS:
        trans.append((U, ch, st[ch], MIN_WORDS_CAP))
        if c2["^" + ch]:
            trans.append((B, ch, st[ch], c2["^" + ch]))
        for nx in LETTERS:
            if c2[ch + nx]:
                trans.append((st[ch], nx, st[nx], c2[ch + nx]))
        if c2[ch + "^"]:
            trans.append((st[ch], " ", B, c2[ch + "^"]))
    trans += [(U, " ", B, MIN_WORDS_CAP), (B, " ", B, MIN_WORDS_CAP)]
    absent = [a + b for a in LETTERS for b in LETTERS if not c2[a + b]]
    lines = header("sieve-filter-v2", "letter-pairs", "lower27",
                   "No two letters side by side inside a word that no word of the list has side by side.", [
                       "Letter pairs: two letters may stand side by side inside a word only if some word of the",
                       "list has them so (and a word may start or end with a letter only if some word does). It",
                       "needs no dictionary of whole words, so names and new words pass while keyboard-mashing",
                       f"mostly does not; at min_words 1 the pairs no word has are: {' '.join(absent)}.",
                       "The start of the unit may be the middle of a word, so its first letter is free. States: 0",
                       "the start, 1 after a SPACE, 2 + n after letter n."], source, sha)
    lines += [f"param     min_words  int  1  1  {MIN_WORDS_CAP}  how many words of the list must have a pair for it to be allowed",
              "", f"states    {2 + 26}", "start     0", f"accept    0..{2 + 25}"]
    return lines + grouped(trans) + ["end"]


def letter_triples(words, sha, source):
    c2, c3 = ngram_counts(words, 2), ngram_counts(words, 3)
    # Contexts (a, x): a is U (unknown, the start of the unit), ^ (a boundary) or a letter.
    U, B = 0, 1
    ctx = ["U", "^"] + list(LETTERS)
    st = {(a, x): 2 + ai * 26 + xi for ai, a in enumerate(ctx) for xi, x in enumerate(LETTERS)}
    trans = [(U, " ", B, MIN_WORDS_CAP), (B, " ", B, MIN_WORDS_CAP)]
    for x in LETTERS:
        trans.append((U, x, st["U", x], MIN_WORDS_CAP))
        if c2["^" + x]:
            trans.append((B, x, st["^", x], c2["^" + x]))
    for a in ctx:
        for x in LETTERS:
            for y in LETTERS + "^":
                n = c2[x + y] if a == "U" else c3[a + x + y]
                if n:
                    trans.append((st[a, x], " " if y == "^" else y, B if y == "^" else st[x, y], n))
    lines = header("sieve-filter-v2", "letter-triples", "lower27",
                   "No three letters in a row inside a word that no word of the list has in a row.", [
                       "Letter triples: three letters may stand in a row inside a word only if some word of the",
                       "list has them so, counting a word's start and end as a letter of their own (so \"^ng\" and",
                       "\"xq^\" are triples too). A much stronger sieve than letter-pairs, still with no dictionary",
                       "of whole words. The start of the unit may be the middle of a word, so its first letters are",
                       "judged by pairs until there are three. States: 0 the start, 1 after a SPACE, then",
                       "2 + a * 26 + x for the last two, a being 0 unknown, 1 a word's start, 2 + n letter n."],
                   source, sha)
    lines += [f"param     min_words  int  1  1  {MIN_WORDS_CAP}  how many words of the list must have a pair or triple for it to be allowed",
              "", f"states    {2 + len(ctx) * 26}", "start     0", f"accept    0..{1 + len(ctx) * 26}"]
    return lines + grouped(trans) + ["end"]


# ---------------------------------------------------------------------------------------------
# Word cost: a letter-pair model of the list, costs in quarter-bits, and a leaky bucket.
#
# P(next | this) counts, over the list's words padded with boundaries, how often `next` follows
# `this` (plus one, so nothing is impossible). A letter's cost is the least whole number of
# quarter-bits q with P >= 2^(-q/4), found by integer comparison (count^4 * 2^q >= total^4), so no
# floating point is involved. The rule: walking a word, e = max(0, e + cost - rate) never passes
# `slack`. That holds exactly when every stretch of the word costs at most rate per letter plus
# slack, so one unlikely run fails a word however long and ordinary its other letters are.


def quarter_bits(count, total):
    k = 0
    while count ** 4 * 2 ** k < total ** 4:
        k += 1
    return k


def word_cost(words, sha, source):
    ctx, outs = ["^"] + list(LETTERS), list(LETTERS) + ["^"]
    cnt = {a: collections.Counter() for a in ctx}
    for w in words:
        p = "^" + w + "^"
        for i in range(len(p) - 1):
            cnt[p[i]][p[i + 1]] += 1
    cost = {}
    for a in ctx:
        total = sum(cnt[a][b] + 1 for b in outs)
        for b in outs:
            cost[a, b] = quarter_bits(cnt[a][b] + 1, total)
    # States: 0 the start (the unit may begin inside a word: its first letter costs nothing), 1
    # after a SPACE, then 2 + n * (slack + 1) + e for letter n with e in the bucket.
    lines = header("sieve-filter-v2", "word-cost", "lower27",
                   "No stretch of a word costs more than the budget under a letter-pair model of the list.", [
                       "Word cost: each letter costs -log2 of its probability after the letter before (or after a",
                       "word's start), and a word's end costs the same after its last letter, in quarter-bits",
                       "rounded up, from a letter-pair model of the list. A word fails when some stretch of it",
                       "costs more than `rate` per letter plus `slack`: kept as a leaky bucket, e = max(0, e +",
                       "cost - rate), which must never pass slack. The countable stand-in for",
                       "model-information-v1, with no dictionary of whole words. Measured on the lists (words",
                       "of 3 to 9 random letters for noise), the defaults keep 99.7% of scowl-en-35's words",
                       "and 98.8% of scowl-en-80-names', and 19% of random words."], source, sha)
    lines += ["param     rate   int  16  4  64  the cost allowed per letter, in quarter-bits (16 is 4 bits)",
              "param     slack  int  40  0  200  how far over the rate a stretch may run, in quarter-bits",
              "", "states    {2 + 26 * (slack + 1)}", "start     0", "accept    0..{1 + 26 * (slack + 1)}",
              't 0 " " 1', 't 1 " " 1']
    for i, x in enumerate(LETTERS):
        lines.append(f"t 0 {q(x)} {{2 + {i} * (slack + 1)}}")
        c = cost["^", x]
        lines += [f"if {{max(0, {c} - rate) <= slack}}",
                  f"  t 1 {q(x)} {{2 + {i} * (slack + 1) + max(0, {c} - rate)}}", "fi"]
    lines.append("for e 0 {slack}")
    for i, a in enumerate(LETTERS):
        here = f"2 + {i} * (slack + 1) + e"
        c = cost[a, "^"]
        lines += [f"  if {{max(0, e + {c} - rate) <= slack}}", f"    t {{{here}}} \" \" 1", "  fi"]
        for j, b in enumerate(LETTERS):
            c = cost[a, b]
            lines += [f"  if {{max(0, e + {c} - rate) <= slack}}",
                      f"    t {{{here}}} {q(b)} {{2 + {j} * (slack + 1) + max(0, e + {c} - rate)}}", "  fi"]
    lines.append("done")
    return lines + ["end"]


# ---------------------------------------------------------------------------------------------
# Function words: the commonest words that hold a sentence together, each a set of its own, and
# every other word of the list in one set (`w`). The rules are the few that real English almost
# never breaks: no function word twice in a row ("the the", "of of"), an article is followed by
# neither an article, a preposition nor a conjunction ("a the", "the of", "an and"), and no two
# conjunctions in a row ("and or"). A page can start or stop anywhere, so any set may be first and
# last.

ARTICLES = ["a", "an", "the"]
PREPOSITIONS = ["at", "by", "for", "from", "in", "into", "of", "on", "onto", "to", "upon", "with"]
CONJUNCTIONS = ["and", "nor", "or"]
FUNCTION_TAGS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def function_words(words, sha, source):
    fw = ARTICLES + PREPOSITIONS + CONJUNCTIONS
    tag = {w: FUNCTION_TAGS[i] for i, w in enumerate(fw)}
    tsv = ["# function-words-v1: every word of the list, folded to lower case, tagged w; the function",
           "# words of function-words-v1.sfilter each tagged with a capital of their own instead.",
           f"# Generated by tools/build_text_plugins.py from {source} (sha256 {sha})."]
    tsv += [f"{w}\t{tag.get(w, 'w')}" for w in sorted(set(words) | set(fw))]
    lines = header("sieve-filter-v1", "function-words", "lower27",
                   "No function word twice in a row, nothing but a word after an article, no two conjunctions.", [
                       "Function words: the commonest words that hold a sentence together each make a set of",
                       "their own, and every other word of the list one set, w. No function word twice in a row",
                       "(\"the the\", \"of of\"); after an article (a, an, the) neither an article, a preposition",
                       "nor a conjunction (\"a the\", \"the of\"); no two conjunctions in a row (\"and or\"). A page",
                       "can start and stop anywhere, so any word may come first and last. Every token must still",
                       "be a word of the list, so this implies words-v2 with the same list."], source, sha)
    lines += ["", "tokens    separator \" \"", "edges     whole", "set       w  tags:function-words-v1.tsv:w"]
    names = {w: ("fw_" + w) for w in fw}
    for w in fw:
        lines.append(f"set       {names[w]}  tags:function-words-v1.tsv:{tag[w]}")
    allsets = ["w"] + [names[w] for w in fw]
    for a in allsets:
        word = a[3:] if a != "w" else None
        for b in allsets:
            other = b[3:] if b != "w" else None
            if word is not None and other == word:
                continue
            if word in ARTICLES and other is not None:
                continue
            if word in CONJUNCTIONS and other in CONJUNCTIONS:
                continue
            lines.append(f"follow    {a}  {b}")
    return lines + ["end"], tsv


# ---------------------------------------------------------------------------------------------
# Sentence shape. Written as a small machine over the characters, then made deterministic here
# (the start of a page can be the middle of anything, so it begins in every state at once) and
# numbered breadth first. The states are (where, owes_capital): where in a word or between words,
# and whether a sentence has just ended so the next word must begin with a capital.

def ascii_class(ch):
    if ch == " ":
        return "space"
    if ch.islower():
        return "lower"
    if ch.isupper():
        return "upper"
    if ch.isdigit():
        return "digit"
    if ch in ",;:":
        return "mid"
    if ch in ".!?":
        return "end"
    if ch == "'":
        return "apos"
    if ch == '"':
        return "quote"
    if ch in "([":
        return "open"
    if ch in ")]":
        return "close"
    if ch == "-":
        return "hyphen"
    return "other"


def shape_step(state, cls, ch, capitals):
    """One step of the machine, or None (dead). States: ('space', owes), ('word', kind, owes) with
    kind lower/cap1/caps/digit, ('mid',), ('end', run, ch), ('open', owes), ('close', ended),
    ('apos',), ('hyphen', after_word), ('dash',)."""
    owes = capitals and state[-1] is True and state[0] in ("space", "open")
    kind = state[0]
    word_like = kind == "word" or (kind == "apos")
    if cls == "space":
        if kind in ("space", "word", "mid", "close"):
            return ("space", (kind == "space" and state[1]) or (kind == "close" and state[1]))
        if kind == "end":
            return ("space", True)
        if kind == "hyphen":
            return ("space", False) if not state[1] else None  # "word- " is not a word
        if kind == "dash":
            return ("space", False)
        if kind == "apos":
            return ("space", False)  # the dogs' bowls
        return None
    if cls in ("lower", "upper", "digit", "other"):
        if kind in ("space", "open"):
            if cls == "lower" and owes:
                return None
            if cls == "upper":
                return ("word", "cap1", False)
            return ("word", "digit" if cls in ("digit", "other") else "lower", False)
        if kind == "word":
            w = state[1]
            if cls == "upper":
                return ("word", "caps", False) if w in ("cap1", "caps") else None
            if cls == "lower" and w == "caps":
                return None  # "HEllo"
            return ("word", "digit" if cls in ("digit", "other") else ("caps" if w == "caps" else "lower"), False)
        if kind in ("apos", "hyphen", "dash"):
            if cls == "upper" and kind == "apos":
                return None  # "don'T"
            return ("word", "cap1" if cls == "upper" else ("digit" if cls in ("digit", "other") else "lower"), False)
        if kind == "end" and state[1] == 1 and state[2] == ".":
            # "e.g.", "U.S.", "3.14": a full stop inside a word or a number.
            return ("word", "cap1" if cls == "upper" else ("digit" if cls in ("digit", "other") else "lower"), False)
        return None
    if cls == "mid":
        return ("mid",) if kind in ("word", "close", "apos") else None
    if cls == "end":
        if kind in ("word", "close", "apos"):
            return ("end", 1, ch)
        if kind == "end" and state[1] < 3:
            return ("end", state[1] + 1, ch)
        return None
    if cls == "apos":
        if kind == "word":
            return ("apos",)
        if kind in ("space", "open"):
            return ("open", state[-1])
        if kind in ("end", "mid", "close"):
            return ("close", kind == "end" or (kind == "close" and state[1]))
        return None
    if cls == "quote":
        if kind in ("space", "open"):
            return ("open", state[-1])
        if kind in ("word", "end", "mid", "close", "apos"):
            return ("close", kind == "end" or (kind == "close" and state[1]))
        return None
    if cls == "open":
        return ("open", state[-1]) if kind in ("space", "open") else None
    if cls == "close":
        if kind in ("word", "end", "close", "apos"):
            return ("close", kind == "end" or (kind == "close" and state[1]))
        return None
    if cls == "hyphen":
        if kind == "word":
            return ("hyphen", True)
        if kind == "hyphen":
            return ("dash",)  # a dash, "--", after a word or a SPACE
        if kind in ("space", "open"):
            return ("hyphen", False)  # "-5", "- item"
        return None
    raise AssertionError(cls)


def shape_starts():
    """Every state a page can begin in (it may be cut from anywhere), owing no capital."""
    return [("space", False), ("word", "lower", False), ("word", "cap1", False), ("word", "caps", False),
            ("word", "digit", False), ("mid",), ("end", 1, "."), ("open", False), ("close", False), ("apos",),
            ("hyphen", True), ("hyphen", False), ("dash",)]


def determinise(alphabet, classify, starts, step):
    """Subset construction over a machine given by `step`; returns (states, transitions) with
    states numbered breadth first and transitions as {(from, char): to}."""
    start = frozenset(starts)
    index, order, trans = {start: 0}, [start], {}
    i = 0
    while i < len(order):
        cur = order[i]
        for ch in alphabet:
            nxt = frozenset(t for s in cur for t in [step(s, classify(ch), ch)] if t is not None)
            if not nxt:
                continue
            if nxt not in index:
                index[nxt] = len(order)
                order.append(nxt)
            trans[index[cur], ch] = index[nxt]
        i += 1
    return order, trans


def quoted(chars):
    """Characters as one quoted token, with " and \\ escaped by a backslash."""
    return '"' + "".join("\\" + c if c in '"\\' else c for c in chars) + '"'


def emit_table(order, trans, alphabet, special=None):
    """Transitions as t lines, each state's symbols to one target joined into one quoted token
    (or a class), and `special` symbols (a dict ch -> class) behind their own lines."""
    lines = []
    for s in range(len(order)):
        by = collections.defaultdict(list)
        for ch in alphabet:
            if (s, ch) in trans:
                by[trans[s, ch]].append(ch)
        for t in sorted(by):
            plain = [c for c in by[t] if not (special and c in special)]
            if plain:
                lines.append(f"t {s} {quoted(plain)} {t}")
            for c in by[t]:
                if special and c in special:
                    lines.append(f"if {{{special[c]}}}")
                    lines.append(f"  t {s} {quoted(c)} {t}")
                    lines.append("fi")
    return lines


def sentence_shape(sha, source):
    alphabet = [chr(c) for c in range(0x20, 0x7F)]
    others = {c: "others == 1" for c in alphabet if ascii_class(c) == "other"}
    order, trans = determinise(alphabet, ascii_class, shape_starts(),
                               lambda s, cls, ch: shape_step(s, cls, ch, True))
    order2, trans2 = determinise(alphabet, ascii_class, shape_starts(),
                                 lambda s, cls, ch: shape_step(s, cls, ch, False))
    lines = ["sieve-filter-v2",
             "; Sentence shape, for pages of printable ASCII: punctuation and capitals where sentences put",
             "; them. , ; : follow a word (or a closing bracket or quote) and are followed by a SPACE or a",
             "; closer; . ! ? the same, up to three in a row (\"...\", \"?!\"), and a single . may be followed",
             "; at once by a letter or digit (\"e.g.\", \"U.S.\", \"3.14\"); no SPACE before any of them. A",
             "; capital starts a word or follows a capital (\"HELLO\"), never a small letter (\"hEllo\").",
             "; With `capitals`, the first word after . ! ? and a SPACE starts with a capital (or a digit",
             "; or bracket), which abbreviations such as \"e.g. the\" break. Brackets and quotes open after a",
             "; SPACE and close after a word; a hyphen joins words (\"well-known\"), and two make a dash.",
             "; The symbols # $ % & * + / < = > @ \\ ^ _ ` { | } ~ count as",
             "; letters when `others` allows them, and fail the page otherwise. A page can start and stop",
             "; anywhere, so its first characters are judged as if anything came before them.",
             "; Generated by tools/build_text_plugins.py (a machine over the characters, made deterministic).",
             "id        sentence-shape", "version   1", f"author    {AUTHOR}", "origin    ai-directed",
             "lines     text", "symbols   ascii95",
             "describe  Punctuation and capitals where sentences put them (pages of printable ASCII).",
             "param     capitals  choice  yes  no,yes  whether a sentence's first word starts with a capital",
             "param     others    choice  no   no,yes  whether # $ % & * + / and the like may appear (as letters)", ""]
    # Two machines, chosen by `capitals`, numbered side by side.
    n1, n2 = len(order), len(order2)
    lines += [f"states    {{(capitals == 1) * {n1} + (capitals == 0) * {n2}}}", "start     0",
              f"accept    0..{{(capitals == 1) * {n1 - 1} + (capitals == 0) * {n2 - 1}}}",
              "if {capitals == 1}"]
    lines += ["  " + l for l in emit_table(order, trans, alphabet, others)]
    lines += ["else"]
    lines += ["  " + l for l in emit_table(order2, trans2, alphabet, others)]
    lines += ["fi", "end"]
    return lines


def babel_class(ch):
    return {" ": "space", ",": "mid", ".": "end"}.get(ch, "lower")


def babel_punctuation(sha, source):
    alphabet = [" "] + list(LETTERS) + [",", "."]
    starts = [("space", False), ("word", "lower", False), ("mid",), ("end", 1, ".")]
    order, trans = determinise(alphabet, babel_class, starts, lambda s, cls, ch: shape_step(s, cls, ch, False))
    lines = ["sieve-filter-v1",
             "; Punctuation for babel29 pages (SPACE, a-z, comma and full stop): a comma or a full stop",
             "; follows a letter and is followed by a SPACE; full stops come up to three in a row (\"...\"),",
             "; and a single one may be followed at once by a letter (\"e.g.\"); no SPACE before either.",
             "; Without it, a babel29 page is mostly commas and full stops in the wrong places. A page can",
             "; start and stop anywhere, so its first characters are judged as if anything came before them.",
             "; Generated by tools/build_text_plugins.py (a machine over the characters, made deterministic).",
             "id        babel-punctuation", "version   1", f"author    {AUTHOR}", "origin    ai-directed",
             "lines     text", "symbols   babel29",
             "describe  Commas and full stops where sentences put them (babel29 pages).", "",
             f"states    {len(order)}", "start     0", f"accept    0..{len(order) - 1}"]
    return lines + emit_table(order, trans, alphabet) + ["end"]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if any written file would differ")
    ap.add_argument("--out", default=OUT)
    a = ap.parse_args()
    wide, wide_sha = words_of("scowl-en-80-names")
    common, common_sha = words_of("scowl-en-60-names")
    wide_src, common_src = "scowl-2020.12.07-en-80-names.txt", "scowl-2020.12.07-en-60-names.txt"
    fw, fw_tsv = function_words(common, common_sha, common_src)
    files = {
        "letter-pairs-v1.sfilter": letter_pairs(wide, wide_sha, wide_src),
        "letter-triples-v1.sfilter": letter_triples(wide, wide_sha, wide_src),
        "word-cost-v1.sfilter": word_cost(wide, wide_sha, wide_src),
        "function-words-v1.sfilter": fw,
        "function-words-v1.tsv": fw_tsv,
        "sentence-shape-v1.sfilter": sentence_shape(None, None),
        "babel-punctuation-v1.sfilter": babel_punctuation(None, None),
    }
    bad = 0
    for name, lines in files.items():
        data = ("\n".join(lines) + "\n").encode("utf-8")
        path = os.path.join(a.out, name)
        if a.check:
            old = open(path, "rb").read() if os.path.exists(path) else b""
            if old != data:
                print(f"differs: {name}")
                bad = 1
            continue
        with open(path, "wb") as f:
            f.write(data)
        print(f"{name}  {len(data)} bytes  sha256 {hashlib.sha256(data).hexdigest()}")
    return bad


if __name__ == "__main__":
    sys.exit(main())
