#!/usr/bin/env python3
"""Writes core/src/unicode_classes.cpp: the code points of the Unicode general categories L (letters)
and N (numbers), as ranges, for the tokenizers of language models (sieve/llm_tokenizer.hpp), whose
pre-tokenizing patterns (\\p{L}, \\p{N}) need them. Generated from Python's unicodedata, whose Unicode
version the file names; run it again to move to another.

    python3 tools/gen_unicode_classes.py > core/src/unicode_classes.cpp
"""
import sys
import unicodedata


def ranges(pred):
    out, start = [], None
    for cp in range(0x110000):
        ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def table(name, rs):
    lines = ["const Range %s[] = {" % name]
    row = []
    for a, b in rs:
        row.append("{0x%X, 0x%X}" % (a, b))
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    cat = lambda cp: unicodedata.category(chr(cp))
    letters = ranges(lambda cp: cat(cp)[0] == "L")
    numbers = ranges(lambda cp: cat(cp)[0] == "N")
    sys.stdout.write("""// Sieve — Unicode letters (general category L) and numbers (N), as ranges of code points, for
// the language models' tokenizers (sieve/llm_tokenizer.hpp). Unicode %s.
// Generated by tools/gen_unicode_classes.py: do not edit by hand.
#include "sieve/unicode_classes.hpp"

#include <algorithm>

namespace sieve::unicode {

namespace {

struct Range
{
    char32_t first, last;
};

%s

%s

template <size_t N>
bool in(const Range (&t)[N], char32_t c)
{
    const Range* r = std::upper_bound(t, t + N, c, [](char32_t v, const Range& x) { return v < x.first; });
    return r != t && c <= (r - 1)->last;
}

} // namespace

const char* version() { return "%s"; }
bool is_letter(char32_t c) { return in(kLetters, c); }
bool is_number(char32_t c) { return in(kNumbers, c); }
bool is_white_space(char32_t c)
{
    // The White_Space property.
    return (c >= 0x09 && c <= 0x0D) || c == 0x20 || c == 0x85 || c == 0xA0 || c == 0x1680 || (c >= 0x2000 && c <= 0x200A) || c == 0x2028 ||
           c == 0x2029 || c == 0x202F || c == 0x205F || c == 0x3000;
}

} // namespace sieve::unicode
""" % (unicodedata.unidata_version, table("kLetters", letters), table("kNumbers", numbers), unicodedata.unidata_version))


if __name__ == "__main__":
    main()
