// Sieve — which code points are letters, numbers and white space, by the Unicode character
// database (core/src/unicode_classes.cpp, generated by tools/gen_unicode_classes.py). For the
// language models' tokenizers (sieve/llm_tokenizer.hpp), whose patterns split text by these.
#pragma once

namespace sieve::unicode {

const char* version();            // the Unicode version the tables are of
bool is_letter(char32_t c);       // general category L (Lu, Ll, Lt, Lm, Lo)
bool is_number(char32_t c);       // general category N (Nd, Nl, No)
bool is_white_space(char32_t c);  // the White_Space property

} // namespace sieve::unicode
