// Sieve — the named Unicode blocks an alphabet can be built from (SPECIFICATIONS §3).
//
// Choose one, or stack several: the code points are unioned, so blocks that overlap (All Emojis
// holds the four emoji blocks; Korean holds Hangul Syllables) can be stacked freely without a
// symbol ever appearing twice.
//
// These ranges are pinned. An alphabet's digits are decided by the code points it holds, so
// widening or narrowing a block here would move every address on every line using it. A
// correction is a new block under a new id.
//
// The table comes from the Gallery of Babel's preset list. Four entries were corrected on the
// way in, before anything was pinned: Old Italic ran to U+1034F and swallowed Gothic; the
// Latin supplement started at U+0081, inside the C1 controls; "Sogdian" carried Old Sogdian's
// range and is named for it; and "Mayan Hieroglyphs" carried the Egyptian range, Maya script
// having no Unicode encoding, so it is not here.
#include "sieve/alphabet.hpp"

namespace sieve {

const std::vector<Block>& blocks()
{
    static const std::vector<Block> table = {
        {"ascii", "ASCII", {0x0020, 0x007E},
         "ASCII, an acronym for American Standard Code for Information Interchange, is a character encoding standard for electronic communication."},
        {"latin-supplement", "Latin-1 Supplement & Extended A + B", {0x00A0, 0x024F},
         "The language of ancient Rome and its empire, widely used historically as a language of scholarship and administration."},
        {"turkish", "Turkish", {0x00C0, 0x00FF},
         "Turkish, the major member of the Turkic language family, spoken in Turkey, Cyprus, and elsewhere in Europe and the Middle East."},
        {"ipa-extensions", "IPA Extensions", {0x0250, 0x02AF},
         "Characters for representing phonetic transcriptions using the International Phonetic Alphabet (IPA)."},
        {"spacing-modifiers", "Spacing Modifier Letters", {0x02B0, 0x02FF},
         "Characters that modify the spacing of adjacent characters, used in phonetic transcriptions and other specialised contexts."},
        {"greek", "Greek", {0x0370, 0x03FF},
         "Greek is the official language of Greece and Cyprus and one of the 24 official languages of the European Union."},
        {"cyrillic", "Cyrillic", {0x0400, 0x04FF},
         "The Cyrillic alphabet is a writing system used in many languages across Eurasia. It is also known as the Slavonic script."},
        {"armenian", "Armenian", {0x0530, 0x058F},
         "Armenians are an ethnic group and nation native to the Armenian highlands of West Asia."},
        {"hebrew", "Hebrew", {0x0590, 0x05FF},
         "Hebrew is a Northwest Semitic language that was spoken in ancient Israel and Judah, and is now the official language of Israel."},
        {"arabic", "Arabic", {0x0600, 0x077F},
         "Arabic is a Semitic language that first appeared in the mid-ninth century BCE in Northern Arabia and the southern Levant."},
        {"syriac", "Syriac", {0x0700, 0x074F},
         "Syriac is a Semitic language that is a dialect of Aramaic and is spoken in parts of the Middle East."},
        {"thaana", "Thaana", {0x0780, 0x07BF},
         "Thaana is the present writing system of the Maldivian language spoken in the Maldives."},
        {"devanagari", "Devanagari", {0x0900, 0x097F}, "Devanagari is an Indic script used in the Indian subcontinent."},
        {"bengali", "Bengali", {0x0980, 0x09FF},
         "Bengali is the national language of Bangladesh and the official language of the Indian states of West Bengal and Tripura. It is also known as Bangla to its speakers."},
        {"gurmukhi", "Gurmukhi", {0x0A00, 0x0A7F},
         "Commonly regarded as a Sikh script, Gurmukhi is used in Punjab, India as the official script of the Punjabi language."},
        {"gujarati", "Gujarati", {0x0A80, 0x0AFF},
         "Gujarati is an Indo-Aryan language native to the Indian state of Gujarat and spoken predominantly by the Gujarati people."},
        {"oriya", "Oriya", {0x0B00, 0x0B7F}, "Oriya is an Indo-European language spoken by about 30 million people in India."},
        {"tamil", "Tamil", {0x0B80, 0x0BFF}, "Tamil is a Dravidian language natively spoken by the Tamil people of South Asia."},
        {"telugu", "Telugu", {0x0C00, 0x0C7F},
         "Telugu is a classical Dravidian language native to the Indian states of Andhra Pradesh and Telangana, where it is also the official language."},
        {"kannada", "Kannada", {0x0C80, 0x0CFF},
         "A classical Dravidian language spoken predominantly by the people of Karnataka in southwestern India, with minorities in all neighbouring states."},
        {"malayalam", "Malayalam", {0x0D00, 0x0D7F},
         "Malayalam is a Dravidian language spoken in the Indian state of Kerala and the union territories of Lakshadweep and Puducherry by the Malayali people."},
        {"sinhala", "Sinhala", {0x0D80, 0x0DFF}, "Sinhala is one of the official and national languages of Sri Lanka."},
        {"thai", "Thai", {0x0E00, 0x0E7F},
         "Thai is the most spoken of over 60 languages of Thailand by both number of native and overall speakers."},
        {"lao", "Lao", {0x0E80, 0x0EFF},
         "Laos, officially the Lao People's Democratic Republic, is the only landlocked country in Southeast Asia."},
        {"tibetan", "Tibetan", {0x0F00, 0x0FFF},
         "Tibetan is spoken in Tibet, parts of China, India, Nepal, Pakistan, Bhutan, and Mongolia. It is part of the Tibeto-Burman language family."},
        {"myanmar", "Myanmar", {0x1000, 0x109F},
         "Myanmar holds characters for the Burmese, Mon, Shan, Palaung, and Karen languages of Myanmar, as well as Aiton and Phake of Northeast India. It is also used to write Pali and Sanskrit in Myanmar."},
        {"georgian", "Georgian", {0x10A0, 0x10FF},
         "Georgian is the most widely spoken Kartvelian language. It is the official language of Georgia and the native or primary language of 88% of its population."},
        {"hangul-jamo", "Hangul Jamo", {0x1100, 0x11FF},
         "Hangul Jamo holds the positional (choseong, jungseong, and jongseong) forms of the Hangul consonant and vowel clusters."},
        {"ethiopic", "Ethiopic", {0x1200, 0x137F},
         "Ethiopic holds characters for writing the Ge'ez, Tigrinya, Amharic, Tigre, Harari, Gurage and other Ethiosemitic languages."},
        {"cherokee", "Cherokee", {0x13A0, 0x13FF},
         "The Cherokee people are one of the Indigenous peoples of the Southeastern Woodlands of the United States."},
        {"canadian-aboriginal", "Unified Canadian Aboriginal", {0x1400, 0x167F},
         "Canadian syllabic writing, or simply syllabics, is a family of writing systems used in a number of indigenous Canadian languages of the Algonquian, Inuit, and Athabaskan language families."},
        {"ogham", "Ogham", {0x1680, 0x169F},
         "Ogham is an alphabet that appears on monumental inscriptions dating from the 4th to the 6th century AD, and in manuscripts dating from the 6th to the 9th century."},
        {"runic", "Runic", {0x16A0, 0x16FF}, "Runic holds the characters for writing Futhark runic inscriptions."},
        {"khmer", "Khmer", {0x1780, 0x17FF},
         "Khmer is an Austroasiatic language spoken natively by the Khmer people. It is the official and national language of Cambodia."},
        {"mongolian", "Mongolian", {0x1800, 0x18AF},
         "Mongolia, a nation bordered by China and Russia, is known for vast, rugged expanses and nomadic culture."},
        {"sundanese", "Sundanese", {0x1B80, 0x1BBF}, "Sundanese is a Malayo-Polynesian language spoken by the Sundanese people."},
        {"latin-extended-additional", "Latin Extended Additional", {0x1E00, 0x1EFF},
         "Additional characters for writing in the Latin script, including letters and symbols not found in the basic Latin alphabet."},
        {"greek-extended", "Greek Extended", {0x1F00, 0x1FFF},
         "Greek Extended holds the accented vowels necessary for writing polytonic Greek."},
        {"general-punctuation", "General Punctuation", {0x2000, 0x206F},
         "Characters for general punctuation, including quotation marks, dashes, and other common punctuation marks."},
        {"superscripts-subscripts", "Superscripts and Subscripts", {0x2070, 0x209F},
         "Characters for writing superscripts and subscripts, used in mathematical and scientific notation."},
        {"currency-symbols", "Currency Symbols", {0x20A0, 0x20CF},
         "Currency symbols are visual representations of a currency unit. They are often used on price tags and receipts."},
        {"letterlike-symbols", "Letterlike Symbols", {0x2100, 0x214F},
         "Characters that resemble letters but are used as symbols, including characters for numbers, fractions, and other mathematical concepts."},
        {"number-forms", "Number Forms", {0x2150, 0x218F},
         "Characters for writing numbers in different forms, including Roman numerals and other specialised number systems."},
        {"arrows", "Arrows", {0x2190, 0x21FF},
         "Characters representing different types of arrows, including single-headed, double-headed, and curved arrows, used for indicating direction, movement, or relationships between objects."},
        {"math-operators", "Mathematical Operators", {0x2200, 0x22FF},
         "Characters for mathematical operators, including symbols for arithmetic, algebra, and other mathematical operations."},
        {"misc-technical", "Miscellaneous Technical", {0x2300, 0x23FF},
         "Characters for technical and scientific notation, including symbols for units, measurements, and other specialised concepts."},
        {"enclosed-alphanumerics", "Enclosed Alphanumerics", {0x2460, 0x24FF},
         "Characters for enclosing alphanumeric characters, including parentheses, brackets, and other enclosing characters."},
        {"box-drawing", "Box Drawing", {0x2500, 0x257F},
         "Characters for creating box-like structures, including borders, corners, and intersections, used for drawing tables, frames, and other rectangular shapes."},
        {"block-elements", "Block Elements", {0x2580, 0x259F},
         "Characters for creating larger patterns and designs using blocks of different sizes and shapes, used for charts, graphs, and other visual representations of data."},
        {"geometric-shapes", "Geometric Shapes", {0x25A0, 0x25FF},
         "Characters representing various geometric shapes, including squares, circles, triangles, and more, used for diagrams, illustrations, and other visual aids."},
        {"misc-symbols", "Miscellaneous Symbols", {0x2600, 0x26FF},
         "Characters for miscellaneous symbols, including symbols for weather, emotions, and other concepts."},
        {"dingbats", "Dingbats", {0x2700, 0x27BF},
         "Dingbats holds typographical ornaments, such as the floral heart character."},
        {"braille", "Braille Patterns", {0x2800, 0x28FF},
         "Characters for Braille patterns, including symbols for reading and writing in Braille."},
        {"cjk-radicals-supplement", "CJK Radicals Supplement", {0x2E80, 0x2EFF},
         "Characters for CJK (Chinese, Japanese, and Korean) radicals, including symbols for components of CJK characters."},
        {"kangxi-radicals", "Kangxi Radicals", {0x2F00, 0x2FDF},
         "A set of 214 radicals that were collated in the 18th-century Kangxi Dictionary to aid categorisation of Chinese characters."},
        {"ideographic-description", "Ideographic Description Characters", {0x2FF0, 0x2FFF},
         "Characters for describing ideographs, including symbols for components and variants of CJK characters."},
        {"cjk-symbols-punctuation", "CJK Symbols and Punctuation", {0x3000, 0x303F},
         "Characters for CJK symbols and punctuation, including punctuation, currency, and other concepts."},
        {"hiragana", "Japanese (Hiragana)", {0x3040, 0x309F},
         "Hiragana is a Japanese syllabary, part of the Japanese writing system, along with Katakana as well as Kanji."},
        {"katakana", "Japanese (Katakana)", {0x30A0, 0x30FF},
         "Katakana is a Japanese syllabary, part of the Japanese writing system, along with Hiragana as well as Kanji."},
        {"japanese-kana", "Japanese (Hiragana & Katakana)", {0x3040, 0x30FF},
         "Hiragana and Katakana are parts of the Japanese writing system, along with Kanji. Holds both of the kana blocks."},
        {"bopomofo", "Bopomofo", {0x3100, 0x31BF},
         "Bopomofo, also called Zhuyin Fuhao or simply Zhuyin, is a transliteration system for Standard Chinese and other Sinitic languages."},
        {"hangul-compatibility-jamo", "Hangul Compatibility Jamo", {0x3130, 0x318F},
         "Characters for compatibility with older Hangul character sets, including jamo and other symbols for writing in the Hangul script."},
        {"kanbun", "Kanbun", {0x3190, 0x319F},
         "Kanbun ('Han writing') is a system for writing Literary Chinese used in Japan from the Nara period until the 20th century."},
        {"enclosed-cjk", "Enclosed CJK Letters and Months", {0x3200, 0x32FF},
         "Characters for enclosing CJK letters and months, including parentheses, brackets, and other enclosing characters."},
        {"cjk-compatibility", "CJK Compatibility", {0x3300, 0x33FF},
         "Characters for CJK compatibility, including symbols for compatibility with older character sets and systems."},
        {"cjk-ext-a", "CJK Unified Ideographs Extension A", {0x3400, 0x4DB5},
         "Additional characters for writing in Chinese, Japanese, and Korean, including extended ideographs and variants."},
        {"chinese", "Chinese (CJK Unified Ideographs)", {0x4E00, 0x9FFF},
         "Chinese is a group of languages spoken natively by the ethnic Han Chinese majority and many minority ethnic groups in China. This is the main CJK Unified Ideographs block."},
        {"yi-syllables", "Yi Syllables", {0xA000, 0xA48F},
         "Characters for writing in the Yi script, including syllables and other characters."},
        {"yi-radicals", "Yi Radicals", {0xA490, 0xA4CF}, "Characters for Yi radicals, including components of Yi characters."},
        {"javanese", "Javanese", {0xA980, 0xA9DF},
         "Javanese is a Malayo-Polynesian language of the Austronesian family spoken primarily by the Javanese people from the central and eastern parts of the island of Java, Indonesia."},
        {"cham", "Cham", {0xAA00, 0xAA5F},
         "Cham is a Malayo-Polynesian language of the Austronesian family, spoken by the Chams of Southeast Asia."},
        {"hangul-syllables", "Hangul Syllables", {0xAC00, 0xD7A3},
         "Characters for writing in the Hangul script, including syllables and other symbols for representing words and phrases in Korean."},
        {"korean", "Korean", {0xAC00, 0xD7AF},
         "Korean is the native language for about 81 million people, mostly of Korean descent. Holds the Hangul Syllables block and the unassigned points after it."},
        {"high-surrogates", "High Surrogates", {0xD800, 0xDBFF},
         "High surrogate code points. Surrogates are bit patterns used in the UTF-16 encoding of Unicode to mark a 16-bit field that does not encode a complete code point by itself. They have no glyph and no UTF-8 encoding, so units holding one can be addressed and drawn but not written out as text."},
        {"low-surrogates", "Low Surrogates", {0xDC00, 0xDFFF},
         "Low surrogate code points. Surrogates are bit patterns used in the UTF-16 encoding of Unicode to mark a 16-bit field that does not encode a complete code point by itself. They have no glyph and no UTF-8 encoding, so units holding one can be addressed and drawn but not written out as text."},
        {"surrogates", "All Surrogates", {0xD800, 0xDFFF},
         "High and low surrogate code points together. They have no glyph and no UTF-8 encoding, so units holding one can be addressed and drawn but not written out as text."},
        {"cjk-compatibility-ideographs", "CJK Compatibility Ideographs", {0xF900, 0xFAFF},
         "Characters for CJK compatibility ideographs, including symbols for compatibility with older character sets and systems."},
        {"alphabetic-presentation-forms", "Alphabetic Presentation Forms", {0xFB00, 0xFB4F},
         "Characters for alphabetic presentation forms, including symbols for displaying letters and other characters in a specific way."},
        {"arabic-presentation-forms-a", "Arabic Presentation Forms, A", {0xFB50, 0xFDFF},
         "Characters for Arabic presentation forms, including symbols for displaying Arabic text in a specific way."},
        {"combining-half-marks", "Combining Half Marks", {0xFE20, 0xFE2F},
         "Characters for combining half marks, including symbols for modifying adjacent characters."},
        {"cjk-compatibility-forms", "CJK Compatibility Forms", {0xFE30, 0xFE4F},
         "Characters for CJK compatibility forms, including symbols for compatibility with older character sets and systems."},
        {"small-form-variants", "Small Form Variants", {0xFE50, 0xFE6F},
         "Characters for small form variants, including symbols for displaying characters in a smaller size."},
        {"arabic-presentation-forms-b", "Arabic Presentation Forms, B", {0xFE70, 0xFEFE},
         "Characters for Arabic presentation forms, including symbols for displaying Arabic text in a specific way."},
        {"halfwidth-fullwidth", "Halfwidth and Fullwidth Forms", {0xFF00, 0xFFEF},
         "Characters for halfwidth and fullwidth forms, including symbols for displaying characters in a specific width."},
        {"ancient-roman", "Ancient Roman", {0x10190, 0x101CF},
         "Ancient Symbols holds characters used to represent numbers, weights and measures as used in ancient Rome."},
        {"old-italic", "Old Italic", {0x10300, 0x1032F},
         "Old Italic holds a unified repertoire of several Old Italic scripts used in various parts of Italy starting about 700 BCE, including the Etruscan alphabet and others derived from or cognate with it."},
        {"gothic", "Gothic", {0x10330, 0x1034F}, "Gothic holds the characters for writing the East Germanic Gothic language."},
        {"old-persian", "Old Persian", {0x103A0, 0x103DF},
         "Old Persian is one of two directly attested Old Iranian languages and is the ancestor of Middle Persian."},
        {"old-south-arabian", "Old South Arabian", {0x10A60, 0x10A7F},
         "Old South Arabian is a group of four closely related extinct languages spoken in the far southern portion of the Arabian Peninsula."},
        {"avestan", "Avestan", {0x10B00, 0x10B3F},
         "Avestan is an Iranian language that belongs to the Indo-European language family. It is closely related to Sanskrit."},
        {"phoenician", "Phoenician", {0x10900, 0x1091F},
         "Phoenician belongs to the Canaanite languages and as such is quite similar to Biblical Hebrew and other languages of the group."},
        {"old-sogdian", "Old Sogdian", {0x10F00, 0x10F2F},
         "Sogdian was an Eastern Iranian language spoken mainly in the Central Asian region of Sogdia, in modern-day Uzbekistan, Tajikistan, Kazakhstan and Kyrgyzstan, and by Sogdian immigrant communities in ancient China."},
        {"cuneiform", "Cuneiform", {0x12000, 0x123FF},
         "Cuneiform is a logo-syllabic writing system that was used to write several languages of the Ancient Near East."},
        {"egyptian-hieroglyphs", "Egyptian Hieroglyphs", {0x13000, 0x1342F},
         "Ancient Egyptian hieroglyphs were the formal writing system used in Ancient Egypt for writing the Egyptian language."},
        {"misc-symbols-pictographs", "Miscellaneous Symbols & Pictographs", {0x1F300, 0x1F5FF},
         "Weather symbols, plants, animals, food, and other pictographs."},
        {"emoticons", "Emoticons", {0x1F600, 0x1F64F}, "Faces, smiles, gestures, and other common emoticons."},
        {"transport-map", "Transport & Map Symbols", {0x1F680, 0x1F6FF},
         "Vehicles, transportation, map symbols, and related pictographs."},
        {"supplemental-symbols-pictographs", "Supplemental Symbols & Pictographs", {0x1F900, 0x1F9FF},
         "Additional faces, hands, animals, body parts, and other pictographs."},
        {"symbols-pictographs-ext-a", "Symbols & Pictographs Extended-A", {0x1FA70, 0x1FAFF},
         "More modern symbols, including gestures, objects, and extended pictographs."},
        {"all-emojis", "All Emojis", {0x1F300, 0x1FAFF},
         "Every emoji block at once: faces, objects, animals, symbols, transport, and more. Holds Emoticons, Miscellaneous Symbols & Pictographs, Transport & Map Symbols, Supplemental Symbols & Pictographs and Symbols & Pictographs Extended-A."},
        {"basic-unicode", "Basic Unicode Range", {0x0020, 0xFFFD},
         "The basic multilingual plane from the space onwards: most living scripts, and the surrogates with them."},
        {"full-unicode", "Full Unicode Range", {0x0020, 0x10FFFF},
         "The full range of Unicode values from the space onwards, most of which are unassigned."},
    };
    return table;
}

const Block* block_by_id(std::string_view id)
{
    for (const Block& b : blocks())
        if (b.id == id) return &b;
    return nullptr;
}

std::vector<std::string> block_ids()
{
    std::vector<std::string> ids;
    for (const Block& b : blocks()) ids.emplace_back(b.id);
    return ids;
}

} // namespace sieve
